Implement `toDot` Method and File Storing Mechanism for `VerkleTrie`
hyperledger/besu-verkle-trie pull request #21
Opened 2023-11-23 07:56 UTC by neotheprogramist

fixes https://github.com/neotheprogramist/besu-verkle-trie/issues/3

2023-11-27 18:18 UTC, Uacias commented
The flag showRepeatingEdges (here I admit that the variable name does not accurately convey the actual intention) was supposed to be responsible for eliminating the edges that disrupted the visibility of the graph, for example, (InternalNode → NullNode, e.g., 240 times).

After carefully considering the feedback, I  certainly agree with the suggestion to change the flag to showNullNodes and modify the functionality to allow displaying the tree with NullNodes/NullLeafNodes or without them.

Thank you for bringing this to my attention, and a revised version in accordance with the feedback will be provided soon.

2023-11-29 10:29 UTC, thomas-quadratic reviewed
Thanks, I tested it and it seems to work fine.
I think we can merge it now (although I do not have those rights).

2023-11-29 11:01 UTC, matkt approved these changes

2023-11-29 11:03 UTC, matkt requested changes
Just fixing this small comment and I will merge it. thanks for your PR

2023-11-29 11:03 UTC, matkt commented on src/test/java/org/hyperledger/besu/ethereum/trie/verkle/SimpleVerkleTrieTest.java
> +    System.out.println(trie.toDotTree(true));
could we have an assert ?

2023-11-29 11:03 UTC, matkt commented on src/test/java/org/hyperledger/besu/ethereum/trie/verkle/SimpleVerkleTrieTest.java
> +    System.out.println(trie.toDotTree(true));
same for all test

2023-11-29 11:03 UTC, matkt commented on src/test/java/org/hyperledger/besu/ethereum/trie/verkle/DotDisplayTest.java
> +    // System.out.println(actualTree);
could we remove that

2023-11-29 15:57 UTC, merged